### ISSUE TITLE
Dming you the problem is easier

### ISSUE THREAD

**Issue by CreepthehissRB** [RealHoriuchi/Locking-Program#2]
Dming you the problem is easier than using github ¬_¬

**Comment by RealHoriuchi** [comment]
This is unrelated to the program or any issue.

**Comment by CreepthehissRB** [comment]
IT IS

**Comment by CreepthehissRB** [comment]
IT COUNTS AS AN ISSUE

**Comment by RealHoriuchi** [comment]
And how would that be?

**Comment by CreepthehissRB** [comment]
IT'S EASIER FOR YOU AND FOR ME IF I JUST DM YOU
INSTEAD OF YOU HAVING TO CLICK THE SITE
REPLY
AND CLOSE THE THREAD XD

**Comment by CreepthehissRB** [comment]
HAVE U NO COMMON SENC, DAMIT

**Comment by RealHoriuchi** [comment]
Please do not make useless issues like this.
